export const API_URL = "http://localhost:8082"
export const TOKEN = "TOKEN"
export const ADMIN ="ADMIN"
export const USER ="USER"
export const EMAIL ="email"
export const AUTHORITY ="authority"
export const COMPANY_ID ="companyId"
